title: 小火箭号站｜Shadowrocket共享账号｜小火箭独享账号
description: 小火箭号站提供Shadowrocket小火箭独享账号、小火箭共享ID、小火箭共享账号、美区Apple ID购买与下载教程，专业的小火箭账号交易平台。
url: "https://xiaohuojianzhanghao.github.io"
baseurl: ""
lang: zh-CN
markdown: kramdown
permalink: /:year/:month/:day/:title/
collections:
  articles:
    output: true
    permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
